### ISSUE TITLE
一些問題

### ISSUE THREAD

**Issue by jackwu0329** [phoxwupsh/turto#10]
使用版本: 1.0.1

問題1.
當使用/queue指令放入`https://www.youtube.com/watch?v=DKXPkZTaCqc&list=RDMMDKXPkZTaCqc&start_radio=1`時
(播放清單名稱顯示為My Mix 此清單為YT自動統整的)
使用/playlist指令會提示Invalid Form Body (data.components.0.components.0.options: Must be between 1 and 25 in length.)
也許是因為YT統整的歌曲超出了顯示數量限制(?)

問題2.
當使用/remove指令刪除1到?項目時，會顯示Message too large.
但項目仍會被刪除(1到50貌似會正常顯示，但1到61會顯示如上)

**Comment by phoxwupsh** [comment]
1. 是因為播放清單中的項目超過250個，頁數選單會有超過25個選項，但Discord的選單只能支援最多25個選項才會有這個問題
2. 是因為當一次移除的項目太多，被移除項目的標題總長度超過2000個字才會這樣

這2個問題好像都是跟播放清單太長有一點關聯，我這幾天想一下要怎麼做比較適合，預計下個版本會解決。

**Comment by phoxwupsh** [comment]
以上問題已於v1.1.0中修復，更新到新版本即可解決問題。
