### ISSUE TITLE
除了youtube影片，b站等平台無法播放

### ISSUE THREAD

**Issue by yuhung0330** [phoxwupsh/turto#15]
你好想詢問，除了youtube影片外，其他的都會進來再自動離開語音頻道，無法播放，這個問題是什麼呢。
b站等平台會輸出Firing Error for [0]跟Firing End for [0]，而用yt影片正常是Firing Playable for [0]

![螢幕擷取畫面 2024-10-16 010013](https://github.com/user-attachments/assets/489d2986-32cb-4f89-8d04-9547ac3771ea)

**Comment by phoxwupsh** [comment]
你可以用`/about`查看你的turto版本是多少，如果是v1.1.0或更舊的版本，只要直接更新新版本就可以了。
如果不是，建議可以開[除錯模式](https://github.com/phoxwupsh/turto/blob/main/README.zh-Hant.md#%E9%99%A4%E9%8C%AF%E6%A8%A1%E5%BC%8F)來看看詳情。

**Comment by yuhung0330** [comment]
感謝，更新版本後，可以使用了。但請問目前apple music跟spotify是否都還不支援？

**Comment by phoxwupsh** [comment]
對的這兩個都不支援，或著說這些平台應該不太可能支援。
