### ISSUE TITLE
希望可以把play 跟queue 指令整合一起

### ISSUE THREAD

**Issue by nerdchan** [phoxwupsh/turto#5]
在我的伺服器的朋友們都習慣用其他音樂bot, 他們都已經有個習慣是用play 指令作為一個加歌的指令，但在turbo的play 中，即使現在有在播歌也會直接打斷然後換新歌，不知道是不是bug, 因為看到source code 其實有 
```
// if there is any song in the play list
            msg.reply(
                ctx,
                TurtoMessage::Play {
                    title: meta.title.as_ref().unwrap(),
                },
            )
            .await?; 
```

**Comment by phoxwupsh** [comment]
這個不是bug而是正設，在預設的help指令中其實可以看到`play`的功能是
```
開始播放，如果turto沒有在其他語音頻道的話就會進入你所在的語音頻道，依照狀況不同有以下幾種可能：
1. 有輸入網址(url)的話，會停止目前正在播放的項目(如果有的話)，並開始播放該網址的內容，目前支援YouTube、Bilibili的影片(直播不行)，和Soundcloud的音樂。
2. 如果沒有輸入網址(url)，且當目前有正在播放的項目被暫停時，會繼續播放該項目。
3. 如果沒有輸入網址(url)，目前也沒有暫停的項目，會從頭開始播放播放清單。
```
這是turto設計的本意，當你用`play`指令時它就只會做play這件事情，而不會去做queue的事情。所以我不會在我的turto這邊做這個功能，你可以在你的fork中做這件事。

另外想問一下，你最後提到的那段source code有什麼問題嗎？

**Comment by nerdchan** [comment]
沒有 只是作為一個沒寫過程式的人，我只是以為我提到的source code邏輯是說當在播歌時收到play指令時，會把新曲queue 在歌單裡，所以才以為是bug

**Comment by phoxwupsh** [comment]
這段code要整段一起看，發生在使用`play`指令時未提供網址且沒有被暫停的項目，則會判斷播放清單中是否還有其他待播放的項目
- 若結果為有則會繼續播放清單中的項目，並回覆被播放的項目的標題。
- 若結果為無則代表功能上已經沒有後續需要判斷的條件，所以回覆提示使用者提供網址。

https://github.com/phoxwupsh/turto/blob/f52b97306c76a5db2255ffac7a8335ee85ad5885/src/commands/play.rs#L84C1-L96C10
