### ISSUE TITLE
Can't add whole playlist on docker machine

### ISSUE THREAD

**Issue by SugiuraAyano** [phoxwupsh/turto#9]
[Symptoms]
無法在使用Docker容器正常增加Youtube撥放清單

[Reproduce]
在DC聊天室輸入 ```/queue url:https://www.youtube.com/watch?v=DRTHbutbxEE&list=PLYEH8HAruP4su3jjHrc-Q-9OCMIdt9QCR```
在DC聊天室輸入 ```/playlist```

[Expected]
正常將撥放清單所有歌曲加入queue

[Actual]
無法正常將撥放清單所有歌曲加入queue, 只有在複製撥放清單網址時的歌曲加入 (v=DRTHbutbxEE)

[Log]
none

**Comment by phoxwupsh** [comment]
感謝你回報這個問題，這個問題應該會在下一個版本修復。你可以先用播放清單本身的網址代替，以你的連結為例，可以把```list=PLYEH8HAruP4su3jjHrc-Q-9OCMIdt9QCR```
前面的部分用
```https://www.youtube.com/playlist?```
取代，讓它變成
```https://www.youtube.com/playlist?list=PLYEH8HAruP4su3jjHrc-Q-9OCMIdt9QCR```
然後再
```/queue url:https://www.youtube.com/playlist?list=PLYEH8HAruP4su3jjHrc-Q-9OCMIdt9QCR```
這樣它應該就會正常的加入整個播放清單。

**Comment by phoxwupsh** [comment]
這個問題已於v1.0.1中修復，更新到新版本即可解決問題。
